### ISSUE TITLE
Collaborazione

### ISSUE THREAD

**Issue by mauro-gobbi** [tinbota/tinbota.github.io#13]
Ciao ti segnalo la dashboard che ho realizzato per San Marino https://coronamonitor.it/sanmarino

**Comment by nicorsm** [comment]
Ciao, chiudo la issue in quanto il sito è stato archiviato. I dati aggiornati sono disponibili su https://www.pa.sm/SASVisualAnalyticsViewer/VisualAnalyticsViewer_guest.jsp?reportSBIP=SBIP%3A%2F%2FMETASERVER%2FShared%20Data%2FReportGuest%2FCOVID19%20-%20Cruscotto%20Pubblico(Report)&page=vi1&informationEnabled=false&commentsEnabled=false&reportViewOnly=true&reportContextBar=false
