### ISSUE TITLE
Dati non aggiornati

### ISSUE THREAD

**Issue by ElCresh** [tinbota/tinbota.github.io#14]
Si voleva mettere in luce come l'ultimo aggiornamento dei dati covid disponibile sul sito risulta fermo al 10/07/2020

**Comment by nicorsm** [comment]
Ciao, chiudo la issue in quanto il sito è stato archiviato. I dati aggiornati sono disponibili su https://www.pa.sm/SASVisualAnalyticsViewer/VisualAnalyticsViewer_guest.jsp?reportSBIP=SBIP%3A%2F%2FMETASERVER%2FShared%20Data%2FReportGuest%2FCOVID19%20-%20Cruscotto%20Pubblico(Report)&page=vi1&informationEnabled=false&commentsEnabled=false&reportViewOnly=true&reportContextBar=false
